stages:
  - build


build_project:
  stage: build
  script:
    - xcodebuild clean -project NoLo-AD.xcworkspace -scheme SchemeName | xcpretty
    - xcodebuild test -project NoLo-AD.xcworkspace -scheme SchemeName | xcpretty -s
 