# This file is a template, and might need editing before it works on your project.
# Lifted from: https://about.gitlab.com/2016/03/10/setting-up-gitlab-ci-for-ios-projects/
# This file assumes an own GitLab CI runner, setup on an OS X system.
stages:
  - build
 

build_project:
  stage: build
  script:
    - xcodebuild clean -project NoMADLogin-AD.xcodeproj -scheme NoMADLoginAD | xcpretty
    - xcodebuild build -project NoMADLogin-AD.xcodeproj -scheme NoMADLoginAD | xcpretty -s
